# https://starship.rs/config/ ----> https://github.com/toml-lang/toml
# Ansi colors: https://i.stack.imgur.com/KTSQa.png
# ------------------------------------------------------------------------------

add_newline = false
continuation_prompt = "❯"
format = "[$directory${custom.folder_number}$git_branch$git_status$git_metrics$git_commit$git_state$sudo$package${custom.alfred}$nodejs$python$jobs$memory_usage](bg:black)[](fg:000)$cmd_duration$character$status" # warp does not support right-side formatting

[character]
success_symbol = ""
error_symbol = " [](bold red)"

[sudo]
style = 'fg:green bg:black'
symbol = " "
format = "[$symbol]($style)"
disabled = false

[cmd_duration]
min_time = 2500
format = " [羽$duration](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "/"
truncate_to_repo = true
read_only = "ﮖ  "
read_only_style = "red bg:black"
style = "fg:bright-blue bg:black bold"
format = "[$path]($style) [$read_only]($read_only_style)"

[directory.substitutions]
"/Library/Mobile Documents/com~apple~CloudDocs" = "/ "
"/File Hub" = "/柳"
"Configs/Alfred.alfredpreferences/workflows" = "AlfredPrefs"

[custom.folder_number]
command = "find . -maxdepth 1 -not -name '.git' -not -name '.' -not -name '.DS_Store' | wc -l"
when = "true"
symbol = " "
description = "Number of files (and folders) in the current working directory"
format = '[$symbol$output]($style) '
style = "fg:yellow bg:black bold"

[status]
format = " [$symbol$status]($style)"
disabled = false
symbol = ""


#───────────────────────────────────────────────────────────────────────────────
# git

[git_state] # mostly conflicts or rebasing
style = 'fg:yellow bg:black'

# checkout
[git_commit]
style = "fg:purple bg:black"
only_detached = true
format = "[$hash]($style) "

# branch
[git_branch]
only_attached = true
symbol = ""
style = "fg:purple bg:black bold"
format = "[$symbol$branch]($style) "

# files
[git_status]
untracked = '[+$count ](fg:green bg:black)'
deleted = '[-$count ](fg:red bg:black)'
modified = '[~$count ](fg:dimmed 208 bg:black)'
renamed = '[凜$count ](fg:blue bg:black)'
staged = '[$count ](fg:cyan bg:black)'
conflicted = '[⤱$count ](fg:red bg:black)'
diverged = '[⇈$count ](fg:cyan bg:black)'
ahead = '[⇡$count ](fg:cyan bg:black)'
behind = '[⇣$count ](fg:yellow bg:black)'
ignore_submodules=false
style = 'fg:purple bg:black bold'
format = '[$ahead_behind$conflicted$stashed$staged$untracked$renamed$modified$deleted]($style)'

# lines
[git_metrics]
disabled = false
# only_nonzero_diffs = false
added_style = "fg:green bg:black"
deleted_style = "fg:red bg:black"
format = '(\([+$added]($added_style)/[-$deleted]($deleted_style)\) )'

#───────────────────────────────────────────────────────────────────────────────

[jobs]
symbol = ""
format = "[ +$number $symbol ]($style)"
style = "fg:white bg:black"
symbol_threshold = 1
number_threshold = 2

[memory_usage]
disabled = false
symbol = " "
threshold = 75
format = " [$symbol$ram_pct]($style)"

[package]
format = "[$symbol$version]($style)"
version_format = "$raw"
symbol = " "
style = "fg:dimmed 208 bg:black"

[custom.alfred]
files = ["info.plist"]
command = "plutil -extract version xml1 -o - info.plist | sed -n 4p | cut -d'>' -f2 | cut -d'<' -f1"
symbol = " "
os = "macos"
description = "Version number of Alfred Workflow"
style = "fg:dimmed 208 bg:black"
format = '[](purple) [$symbol$output]($style)'

[nodejs]
format = " [$symbol$version]($style) "
version_format = "$major"
style = "fg:dimmed cyan bg:black"
detect_extensions = ["ts"] # dont trigger for JXA

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "$major.$minor"
style = "fg:dimmed yellow bg:black"
python_binary = ["python3"]
symbol = " "
