# https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
# ------------------------------------------------------------------------------

filter_exex: neovide

extra_exclude:
  - "../match/private.yml"
  - "../match/email.yml"

backend: Clipboard
