# https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
# ------------------------------------------------------------------------------

filter_exex: Neovide

extra_exclude:
  - "../match/private.yml"
  - "../match/email.yml"

backend: clipboard

inject_delay: 1
key_delay: 1
# paste_shortcut: None
# pre_paste_delay: 100
# paste_shortcut_event_delay: 10
# post_form_delay: 200
# post_search_delay: 200
