# https://espanso.org/docs/configuration/app-specific-configurations/
filter_exec: Obsidian

extra_exclude:
  # - "../match/private.yml"
  - "../match/non-vim-apps.yml"
  - "../match/email.yml"

extra_include:
  - "../match/_cheatsheet.yml"
  - "../match/_vim-apps.yml"
