# https://espanso.org/docs/configuration/app-specific-configurations/#disabling-espanso-when-using-a-certain-app
# ------------------------------------------------------------------------------

# disable espanso when using a password manager
# (mostly used as safety net)
filter_exec: MacPass|KeePass
enable: false
