# https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
# ------------------------------------------------------------------------------
# only activates code snippets when a file of the right language is open

filter_exex: Obsidian|Neovide|neovide

extra_exclude:
  - "../match/private.yml"
  - "../match/email.yml"
