# https://docs.warp.dev/features/session-management/launch-configurations#commands
# Warp Launch Configuration
#
# This configuration has two windows.
# The first window executes two commands on start.
# The second window has a split pane that executes a command on start.

---
name: Default
windows:
  - tabs:
      - title: File Hub
        layout:
          cwd: /Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/File Hub/
        color: blue
