# https://dystroy.org/broot
#-------------------------------------------------------------------------------

modal = false # vim-like controls
quit_on_last_cancel = true
default_flags = "igh" # i = show git-ignored, g = show git status, h = show hidden
show_selection_mark = false

[[verbs]]
# Switch Enter and alt+enter from the default config
key = "enter"
internal = ":open_leave"
apply_to = "file"

# ignore paths
[special-paths]
"*/.git" = "hide"
"*/.DS_Store" = "hide"

# copy path/name
[[verbs]]
key = "ctrl-p"
external = "echo \"{file}\" | pbcopy"
from_shell = true
[[verbs]]
key = "ctrl-n"
external = "echo \"{file-name}\" | pbcopy"
from_shell = true

# preview panel
[[verbs]]
key = "alt-enter"
internal = ":open_preview"
apply_to = "file"
[[verbs]]
key = "ctrl-w"
internal = ":close_preview"

# exact search by default
[search_modes]
"<empty>"= "exact name"
"/"= "fuzzy name"

