# https://dystroy.org/broot
#-------------------------------------------------------------------------------

# VIM-LIKE CONTROLS
# note that this must be near the start of the configuration file
modal = true

# QUIT ON LAST CANCEL
# You can usually cancel the last state change on escape. If you want the escape
# key to quit broot when there's nothing to cancel(for example when you just
# opened broot), uncomment this parameter
quit_on_last_cancel = true

default_flags = "ig"
# i = show git-ignored files
# g = show git status

show_selection_mark = false

#-------------------------------------------------------------------------------

# Switch Enter and alt+enter from the default config
[[verbs]]
key = "enter"
internal = ":open_leave"
apply_to = "file"
[[verbs]]
key = "alt-enter"
internal = ":open_stay"
apply_to = "file"

# If $EDITOR isn't set on your computer, you should either set it or just
# replace it with your editor of choice in the 'execution' pattern.
# Example: execution = "/usr/bin/nvim {file}"
# [[verbs]]
# invocation = "edit"
# key = "F2"
# shortcut = "e"
# execution = "$EDITOR {file}"


#-------------------------------------------------------------------------------
# File Extension Colors
# uncomment and modify the next section if you want to color
# file name depending on their extension
#
# ext_colors: {
#     png: rgb(255, 128, 75)
#     rs: yellow
# }


#-------------------------------------------------------------------------------
# Date/Time format
# If you want to change the format for date/time, uncomment the
# following line and change it according to
# https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
#
# date_time_format: %Y/%m/%d %R

#-------------------------------------------------------------------------------
# Column order
# cols_order, if specified, must be a permutation of the following
# array. You should keep the name column at the end as it has a
# variable length.
#
# cols_order: [
#     mark
#     git
#     size
#     permission
#     date
#     count
#     branch
#     name
# ]

#-------------------------------------------------------------------------------
# True Colors
# If this parameter isn't set, broot tries to automatically
# determine whether true colors (24 bits) are available.
# As this process is unreliable, you may uncomment this setting
# and set it to false or true if you notice the colors in
# previewed images are too off.
#
# true_colors: false

#-------------------------------------------------------------------------------
# Icons
# If you want to display icons in broot, uncomment this line
# (see https://dystroy.org/broot/icons for installation and
# troubleshooting)
#
# icon_theme: vscode

#-------------------------------------------------------------------------------
# Special paths
# If some paths must be handled specially, uncomment (and change
# this section as per the examples)
#
# special_paths: {
#     "/media/slow-backup-disk"    : no-enter
#     "/home/dys/useless"    : hide
#     "/home/dys/my-link-I-want-to-explore"    : enter
# }

#-------------------------------------------------------------------------------
# Quit on last cancel
# You can usually cancel the last state change on escape.
# If you want the escape key to quit broot when there's nothing
# to cancel (for example when you just opened broot), uncomment
# this parameter
#
# quit_on_last_cancel: true

#-------------------------------------------------------------------------------
# Search modes
#
# broot allows many search modes.
# A search mode is defined by
# - the way to search: 'fuzzy', 'exact', 'regex', or 'tokens'.
# - where to search: file 'name', 'path', or file 'content'
# A search pattern may for example be "fuzzy path" (default),
# "regex content" or "exact path".
#
# The search mode is selected from its prefix. For example, if
# you type "abc", the default mode is "fuzzy path". If you type
# "/abc", the mode is "regex path". If you type "rn/abc", the mode
# is "regex name".
#
# This mapping may be modified. You may want to dedicate the
# empty prefix (the one which doesn't need a '/') to the
# search mode you use most often. The example below makes it
# easy to search on name rather than on the subpath.
#
# More information on
#  https://dystroy.org/broot/input/#the-filtering-pattern
#
# search_modes: {
#     <empty>: fuzzy name
#     /: regex name
# }

#-------------------------------------------------------------------------------
# File Extension Colors
#
# uncomment and modify the next section if you want to color
# file name depending on their extension
#
# ext_colors: {
#     png: rgb(255, 128, 75)
#     rs: yellow
# }


#-------------------------------------------------------------------------------
# Max Panels Count
#
# Change this if you sometimes want to have more than 2 panels
# open
# max_panels_count: 2

#-------------------------------------------------------------------------------
