extends:
  - eslint:recommended
root: true # stop annoying deprecation warning
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules:
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: all
  no-unused-vars:
    - warn
    - varsIgnorePattern: run
  require-await: error
  camelcase:
    - warn
    - properties: always
      ignoreImports: true

  no-var: error
  prefer-const: warn
  sort-vars: warn
  no-use-before-define: error
  no-multi-assign: error
  no-sequences: error
  no-undefined: error
  one-var-declaration-per-line:
    - error
    - initializations
  prefer-regex-literals:
    - error
    - disallowRedundantWrapping: true
  no-mixed-spaces-and-tabs: warn
  no-empty-function: warn
  indent:
    - warn
    - tab
    - SwitchCase: 1
  no-multi-spaces: warn
  array-bracket-spacing: warn
  space-before-blocks: warn
  semi-spacing: warn
  object-curly-spacing:
    - warn
    - always
  no-whitespace-before-property: error
  no-empty: warn
  arrow-spacing: warn
  keyword-spacing: warn
  spaced-comment:
    - warn
    - always
    - exceptions: ["-", "_", "─"]
  object-curly-newline:
    - warn
    - multiline: true
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 3
  no-multiple-empty-lines:
    - warn
    - max: 2
  no-extra-parens:
    - warn
    - all
    - returnAssign: false
  array-callback-return:
    - error
    - checkForEach: false
      allowImplicit: true
  no-unmodified-loop-condition: error
  no-unreachable-loop: error
  no-await-in-loop: error
  require-atomic-updates: error
  no-useless-return: error
  no-extra-semi: warn
  semi-style:
    - error
    - last
  semi:
    - warn
    - always
    - omitLastInOneLineBlock: true
  comma-spacing: warn
  comma-style: warn
  comma-dangle:
    - error
    - arrays: never
      objects: only-multiline
  quotes:
    - warn
    - double
    - avoidEscape: true
      allowTemplateLiterals: true
  no-useless-concat: warn
  no-multi-str: error
  no-magic-numbers:
    - error
    - ignore: [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 0.1, 0.2, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 100, 1000, 10000, 1024]
      ignoreArrayIndexes: true
  no-floating-decimal: warn
  no-implicit-coercion: error
  eqeqeq: error
  no-eq-null: error
  no-negated-condition: error
  no-unneeded-ternary: error
  no-nested-ternary: error
  yoda: warn
  no-else-return:
    - error
    - allowElseIf: false
  no-lonely-if: error
  no-mixed-operators:
    - error
    - groups:
        - ['%', '**']
        - ['&', '|', ^, "~", <<, '>>', '>>>']
        - [==, '!=', ===, '!==', '>', '>=', <, <=]
        - ['&&', '||']
        - [in, instanceof]
  no-duplicate-imports: warn
  sort-imports: warn
  dot-notation: error
globals:
  # JXA
  console: readonly
  ObjC: readonly
  delay: readonly
  Application: readonly
  $: readonly
  Set: readonly
  Path: readonly
  # Obsidian
  tp: readonly
  request: readonly
  dv: readonly
