# https://kampfkarren.github.io/selene/lints/constant_table_comparison.html
#───────────────────────────────────────────────────────────────────────────────

# disabled since taken care of by lsp
[lints]
undefined_variable = "allow"
unused_variable = "allow"
empty_if = "allow"
unscoped_variables = "allow"
multiple_statements = "allow"

high_cyclomatic_complexity = "warn" # enable this one

[config]
high_cyclomatic_complexity = {maximum_complexity = 13}
