# https://github.com/akiyosi/goneovim/wiki/Usage#configuration

[Editor]
RestoreWindowGeometry = true
BorderlessWindow = true
Margin = 3

FontFamily =  "Input" # only external UI
FontSize = 25

Letterspace = 0
DisableLigatures = true

Macmeta = false
SmoothScroll = true

[Cursor]
SmoothMove = true
Duration = 30
