# https://github.com/akiyosi/goneovim/wiki/Usage#configuration

[Editor]
RestoreWindowGeometry = true
BorderlessWindow = true
Margin = 4
Transparent = 0.97
DrawBorderForFloatWindow = false

FontFamily =  "Recursive" # only external UI
FontSize = 1

Macmeta = false
SmoothScroll = false # glitchy

[Cursor]
SmoothMove = false #glitchy
Duration = 20
