# https://starship.rs/config/ ----> https://github.com/toml-lang/toml
# Ansi colors: https://i.stack.imgur.com/KTSQa.png
# nerd font icons https://www.nerdfonts.com/cheat-sheet

# --------------------------------------------------
# Terminus does not properly support bold, therefore
# separate config file for it
# --------------------------------------------------

add_newline = false
continuation_prompt = "❯"
format = "[$directory${custom.folder_number}$git_branch$git_status$git_metrics$git_commit$git_state](bg:black)[](black)$cmd_duration$status$character"
right_format="$package${custom.alfred}$nodejs$python$jobs$memory_usage"

# ⏼⏻⟐ﰉﰊ
[character]
success_symbol = " [ﰉ ](bold green)"
error_symbol = " [ ](bold red)" # terminus needs extra space
vimcmd_symbol = " [ ](bold blue)"
# https://starship.rs/config/#character
# those don't work due to upstream zsh bug
# vimcmd_visual_symbol = " [V](bold blue)"
# vimcmd_replace_symbol = " [R](bold blue)"
# vimcmd_replace_one_symbol = " [r](bold blue)"

[cmd_duration]
min_time = 2500
format = " [ $duration](bold cyan)"

[directory]
truncation_length = 3
truncation_symbol = "/"
truncate_to_repo = true
read_only = "ﮖ  "
read_only_style = "red bg:black"
style = "fg:bright-blue bg:black" # terminus different
format = "[$path]($style) [$read_only]($read_only_style)"

[directory.substitutions]
"/Library/Mobile Documents/iCloud~md~obsidian/Documents" = "/ "
"/Library/Mobile Documents/com~apple~CloudDocs" = "/ "
"/File Hub" = "/柳 "
"/dotfiles" = "/ "
"Configs/Alfred.alfredpreferences/workflows" = "AlfredPrefs"

[custom.folder_number]
command = "find . -maxdepth 1 -not -name '.git' -not -name '.' -not -name '.DS-Store' | wc -l"
when = "true"
symbol = " "
description = "Number of files (and folders) in the current working directory"
format = '[$symbol$output]($style) '
style = "fg:yellow bg:black" # terminus different

[status]
format = " [$symbol$status]($style)"
disabled = false
symbol = ""

[sudo]
format="[sudo $symbol]($style)"
disabled = false

# -------------
# git
# -------------

[git_state] # mostly conflicts
style = 'fg:blue bg:black'

[git_commit]
style = "fg:yellow bg:black"

# branch
[git_branch]
only_attached = true
symbol = ""
style = "fg:purple bg:black" # terminus different
format = "[$symbol$branch]($style) "

# files
[git_status]
untracked = '[+$count ](fg:green bg:black)'
deleted = '[-$count ](fg:red bg:black)'
modified = '[*$count ](fg:cyan bg:black)'
renamed = '[✎$count ](fg:blue bg:black)'
staged = '[◎$count ](fg:cyan bg:black)'
conflicted = '[⤱$count ](fg:red bg:black)'
diverged = '[⇈$count ](fg:cyan bg:black)'
ahead = '[⇡$count ](fg:cyan bg:black)'
behind = '[⇣$count ](fg:yellow bg:black)'
style = 'fg:purple bg:black' # terminus different
format = '[$ahead_behind$conflicted$stashed$staged$untracked$renamed$modified$deleted]($style)'

# lines
[git_metrics]
disabled = false
added_style = "fg:green bg:black"
deleted_style = "fg:red bg:black"
format = '([\(](dimmed bg:black)[+$added]($added_style)[/](dimmed bg:black)[-$deleted]($deleted_style)[\)](dimmed bg:black))'

# -------------
# right side
# -------------
[jobs]
symbol = ""
format = "[ +$number $symbol ]($style)"
style = "fg:white"
symbol_threshold = 1
number_threshold = 1

[memory_usage]
disabled = false
symbol = " "
threshold = 75
format = " [$symbol$ram_pct]($style)"

[package]
format = "[$symbol$version]($style)"
version_format = " $raw"
symbol = ""
style = "dimmed 208"

[custom.alfred]
command = "plutil -extract version xml1 -o - info.plist | sed -n 4p | cut -d'>' -f2 | cut -d'<' -f1"
files = ["info.plist"]
symbol = " "
os = "macos"
description = "Version number of Alfred Workflow"
style = "dimmed 208"
format = '[Alfred](purple) [$symbol$output]($style)'

[nodejs]
format = " [$symbol$version]($style)"
version_format = "$major"
style = "dimmed cyan"
detect_extensions = ["ts"] # dont trigger for JXA

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "$major.$minor"
style = "dimmed yellow"
python_binary = ["python3"]
symbol = " "

