# https://starship.rs/config/ ----> https://github.com/toml-lang/toml
# Ansi colors: https://i.stack.imgur.com/KTSQa.png
# ------------------------------------------------------------------------------

add_newline = false
continuation_prompt = "❯"
format = "[$directory${custom.folder_number}$git_branch$git_status$git_metrics$git_commit$git_state$sudo](bg:black)$cmd_duration$status$character"

[character]
success_symbol = ""
error_symbol = ""

[sudo]
style = 'fg:green bg:black'
symbol = " "
format = "[$symbol]($style)"
disabled = false

[cmd_duration]
min_time = 2500
format = " [羽$duration](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "/"
truncate_to_repo = true
read_only = "ﮖ  "
read_only_style = "red bg:black"
style = "fg:bright-blue bg:black bold"
format = "[$path]($style) [$read_only]($read_only_style)"

[directory.substitutions]
"/Library/Mobile Documents/com~apple~CloudDocs" = "/ "
"/File Hub" = "/柳"
"dotfiles" = " "
"Configs/Alfred.alfredpreferences/workflows" = "AlfredPrefs"

[custom.folder_number]
command = "find . -maxdepth 1 -not -name '.git' -not -name '.' -not -name '.DS_Store' | wc -l"
when = "true"
symbol = " "
description = "Number of files (and folders) in the current working directory"
format = '[$symbol$output]($style) '
style = "fg:yellow bg:black bold"

[status]
format = " [$symbol$status]($style)"
disabled = false
symbol = ""

# -------------
# git
# -------------

[git_state] # mostly conflicts
style = 'fg:blue bg:black'

# checkout
[git_commit]
style = "fg:purple bg:black"
only_detached = true
format = "[$hash]($style) "

# branch
[git_branch]
only_attached = true
symbol = ""
style = "fg:purple bg:black bold"
format = "[$symbol$branch]($style) "

# files
[git_status]
ignore_submodules=false
untracked = '[+$count ](fg:green bg:black)'
deleted = '[-$count ](fg:red bg:black)'
modified = '[*$count ](fg:cyan bg:black)'
renamed = '[✎$count ](fg:blue bg:black)'
staged = '[◎$count ](fg:cyan bg:black)'
conflicted = '[⤱$count ](fg:red bg:black)'
diverged = '[⇈$count ](fg:cyan bg:black)'
ahead = '[⇡$count ](fg:cyan bg:black)'
behind = '[⇣$count ](fg:yellow bg:black)'
style = 'fg:purple bg:black bold'
format = '[$ahead_behind$conflicted$stashed$staged$untracked$renamed$modified$deleted]($style)'

# lines
[git_metrics]
disabled = false
# only_nonzero_diffs = false
added_style = "fg:green bg:black"
deleted_style = "fg:red bg:black"
format = '(\([+$added]($added_style)/[-$deleted]($deleted_style)\) )'
